import cn from '@/utils/class-names';
import '@/styles/global.css';
import { ThemeProvider } from '@/components/theme-provider';
import PrelineScript from '@/components/PrelineScript';
import { AuthProvider } from '@/hooks/use-auth';
import { inter, lexendDeca } from './fonts';

export const metadata = {
  title: 'Dal Vacation Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }) {
  return (
    <html suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(inter.variable, lexendDeca.variable, 'font-inter')}
      >
        <ThemeProvider>
          <PrelineScript />
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
